"""
System Design IR Models — Stage 2 Output

These models define the Intermediate Representation (IR) generated by
the System Design pass. They map raw feature inventories into actual
architectural dependencies: RBAC, entities, workflows, and feature gates.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# RBAC (Role-Based Access Control)
# ---------------------------------------------------------------------------

class Permission(BaseModel):
    """A single permission in the RBAC matrix."""
    resource: str = Field(description="Resource being controlled, e.g. 'users', 'orders'")
    action: str = Field(description="Action allowed: 'create', 'read', 'update', 'delete', 'list'")

    @property
    def key(self) -> str:
        return f"{self.action}:{self.resource}"


class Role(BaseModel):
    """A role in the system's RBAC matrix."""
    name: str = Field(description="Role identifier, e.g. 'admin', 'premium_user', 'standard_user'")
    description: str = Field(description="What this role represents")
    permissions: list[Permission] = Field(
        default_factory=list,
        description="Permissions granted to this role"
    )
    inherits_from: Optional[str] = Field(
        default=None,
        description="Parent role to inherit permissions from, e.g. 'standard_user'"
    )


# ---------------------------------------------------------------------------
# Data Model / Entity Graph
# ---------------------------------------------------------------------------

class FieldType(str, Enum):
    """Supported abstract field types (mapped to concrete SQL types in Stage 3)."""
    STRING = "string"
    TEXT = "text"
    INTEGER = "integer"
    FLOAT = "float"
    BOOLEAN = "boolean"
    DATETIME = "datetime"
    DATE = "date"
    UUID = "uuid"
    EMAIL = "email"
    URL = "url"
    JSON = "json"
    ENUM = "enum"
    DECIMAL = "decimal"


class EntityField(BaseModel):
    """A single field on a data entity."""
    name: str = Field(description="Snake_case field name, e.g. 'email_address'")
    field_type: FieldType = Field(description="Abstract data type")
    required: bool = Field(default=True, description="Whether this field is required")
    unique: bool = Field(default=False, description="Whether this field must be unique")
    default_value: Optional[str] = Field(default=None, description="Default value if any")
    description: str = Field(default="", description="What this field represents")
    enum_values: Optional[list[str]] = Field(
        default=None,
        description="Allowed values if field_type is 'enum'"
    )


class RelationshipType(str, Enum):
    """Supported relationship types between entities."""
    HAS_MANY = "has_many"
    BELONGS_TO = "belongs_to"
    HAS_ONE = "has_one"
    MANY_TO_MANY = "many_to_many"


class Relationship(BaseModel):
    """A relationship between two entities."""
    target_entity: str = Field(description="The related entity name")
    relationship_type: RelationshipType = Field(description="Type of relationship")
    foreign_key: Optional[str] = Field(
        default=None,
        description="Foreign key field name, auto-generated if not specified"
    )
    cascade_delete: bool = Field(
        default=False,
        description="Whether deleting the parent cascades to this relationship"
    )


class Entity(BaseModel):
    """A data entity in the system design."""
    name: str = Field(description="PascalCase entity name, e.g. 'UserProfile'")
    description: str = Field(description="What this entity represents")
    fields: list[EntityField] = Field(
        default_factory=list,
        description="Fields on this entity (excluding auto-generated id, timestamps)"
    )
    relationships: list[Relationship] = Field(
        default_factory=list,
        description="Relationships to other entities"
    )
    is_user_facing: bool = Field(
        default=True,
        description="Whether this entity is directly exposed via API"
    )


# ---------------------------------------------------------------------------
# Feature Gates
# ---------------------------------------------------------------------------

class FeatureGate(BaseModel):
    """A gated feature requiring specific role access."""
    feature: str = Field(description="Feature identifier matching a FeatureSpec.name")
    required_role: str = Field(description="Minimum role required to access this feature")
    enabled_by_default: bool = Field(
        default=True,
        description="Whether this feature is enabled by default for qualifying roles"
    )
    description: str = Field(default="", description="Why this gate exists")


# ---------------------------------------------------------------------------
# Workflows (Multi-step business processes)
# ---------------------------------------------------------------------------

class WorkflowStepType(str, Enum):
    """Types of workflow steps."""
    USER_ACTION = "user_action"
    SYSTEM_ACTION = "system_action"
    VALIDATION = "validation"
    NOTIFICATION = "notification"
    EXTERNAL_CALL = "external_call"
    CONDITIONAL = "conditional"


class WorkflowStep(BaseModel):
    """A single step in a multi-step workflow."""
    order: int = Field(description="Execution order (1-indexed)")
    name: str = Field(description="Step identifier")
    step_type: WorkflowStepType = Field(description="What kind of step this is")
    description: str = Field(description="What happens in this step")
    entity_involved: Optional[str] = Field(
        default=None,
        description="Primary entity this step operates on"
    )
    required_role: Optional[str] = Field(
        default=None,
        description="Role required to execute this step"
    )


class Workflow(BaseModel):
    """A multi-step business process."""
    name: str = Field(description="Workflow identifier, e.g. 'order_checkout_flow'")
    description: str = Field(description="What this workflow accomplishes")
    trigger: str = Field(description="What initiates this workflow, e.g. 'user clicks checkout'")
    steps: list[WorkflowStep] = Field(description="Ordered steps in the workflow")


# ---------------------------------------------------------------------------
# Complete System Design IR
# ---------------------------------------------------------------------------

class SystemDesignIR(BaseModel):
    """
    The complete Intermediate Representation from Stage 2: System Design.

    This is the architectural blueprint that Stage 3 (Schema Generation)
    consumes to produce concrete DB, API, and UI schemas.
    """
    roles: list[Role] = Field(
        description="RBAC matrix — all roles and their permissions"
    )
    entities: list[Entity] = Field(
        description="Data model graph — all entities with fields and relationships"
    )
    feature_gates: list[FeatureGate] = Field(
        default_factory=list,
        description="Feature access control gates"
    )
    workflows: list[Workflow] = Field(
        default_factory=list,
        description="Multi-step business process definitions"
    )

    def get_entity(self, name: str) -> Optional[Entity]:
        """Look up an entity by name (case-insensitive)."""
        for entity in self.entities:
            if entity.name.lower() == name.lower():
                return entity
        return None

    def get_role(self, name: str) -> Optional[Role]:
        """Look up a role by name (case-insensitive)."""
        for role in self.roles:
            if role.name.lower() == name.lower():
                return role
        return None

    @property
    def entity_names(self) -> list[str]:
        """All entity names in the design."""
        return [e.name for e in self.entities]

    @property
    def role_names(self) -> list[str]:
        """All role names in the design."""
        return [r.name for r in self.roles]

    def to_context_summary(self) -> dict:
        """Returns a compressed dictionary representation of the design IR to save tokens."""
        return {
            "roles": [r.name for r in self.roles],
            "entities": {
                e.name: [{"name": f.name, "type": f.field_type.value} for f in e.fields]
                for e in self.entities
            },
            "relationships": [
                f"{e.name}_{r.relationship_type.value}_{r.target_entity}"
                for e in self.entities for r in e.relationships
            ],
            "workflows": [w.name for w in self.workflows]
        }
